import { Injectable, signal } from '@angular/core';
import '../shared/interfaces.ts';

@Injectable({
  providedIn: 'root',
})
export class DataStoreServiceService {

  public settings = signal<any>({});

  public balance = signal<BalanceObject>({
    balance: 10060.98,
  });

  // public budgets = signal<BudgetsObject[]>([]);

  public budgets = signal<BudgetsObject[]>([
    {
      id: 1,
      name: 'Transportation',
      amount: 56.26,
      maximum: 419,
      theme: '#93674F',
      time_frame: 'month',
      deleted_at: null,
      created_at: '2025-02-24T16:14:01.000000Z',
      last_spendings: [
        {
          transaction_id: 1,
          user_id: 1,
          sender: '',
          receiver: '',
          name: 'Initial Deposit',
          amount: 100.0,
          recurring: null,
          recurring_id: null,
          theme: '#d46c5e',
          budget_id: null,
          deleted_at: null,
          created_at: '2025-02-24T16:14:01.000000Z',
          execute_on: '2025-12-19T00:00:00Z',
          type: 'credit',
          category: 'transportation',
        },
        {
          transaction_id: 2,
          user_id: 1,
          sender: '',
          receiver: '',
          name: 'Veum-Dare',
          amount: 20.26,
          recurring: null,
          recurring_id: null,
          theme: '#3f82b2',
          budget_id: 4,
          deleted_at: null,
          created_at: '2025-02-24T16:14:01.000000Z',
          execute_on: '2025-12-19T00:00:00Z',
          type: 'credit',
          category: 'transportation',
        },
      ],
    },
    {
      id: 2,
      name: 'Groceries',
      amount: 397.54,
      maximum: 350,
      theme: '#82C9D7',
      time_frame: 'half',
      deleted_at: null,
      created_at: '2025-02-24T16:14:01.000000Z',
      last_spendings: [
        {
          transaction_id: 1,
          user_id: 1,
          sender: '',
          receiver: '',
          name: 'Initial Deposit',
          amount: 100.0,
          recurring: null,
          recurring_id: null,
          theme: '#626070',
          budget_id: null,
          deleted_at: null,
          created_at: '2025-02-24T16:14:01.000000Z',
          execute_on: '2025-12-19T00:00:00Z',
          type: 'credit',
          category: 'groceries',
        },
        {
          transaction_id: 2,
          user_id: 1,
          sender: '',
          receiver: '',
          name: 'Veum-Dare',
          amount: 20.26,
          recurring: null,
          recurring_id: null,
          theme: '#277c78',
          budget_id: 4,
          deleted_at: null,
          created_at: '2025-02-24T16:14:01.000000Z',
          execute_on: '2025-12-19T00:00:00Z',
          type: 'credit',
          category: 'groceries',
        },
      ],
    },
    {
      id: 3,
      name: 'Bills',
      amount: 69.29,
      maximum: 267.59,
      theme: '#934F6F',
      time_frame: 'month',
      deleted_at: null,
      created_at: '2025-02-24T16:14:01.000000Z',
      last_spendings: null,
    },
    {
      id: 4,
      name: 'Shopping',
      amount: 207.74,
      maximum: 602.07,
      theme: '#F2CDAC',
      time_frame: 'year',
      deleted_at: null,
      created_at: '2025-02-24T16:14:01.000000Z',
      last_spendings: [
        {
          transaction_id: 1,
          user_id: 1,
          sender: '',
          receiver: '',
          name: 'Initial Deposit',
          amount: 100.0,
          recurring: null,
          recurring_id: null,
          theme: '#be6c49',
          budget_id: null,
          deleted_at: null,
          created_at: '2025-02-24T16:14:01.000000Z',
          execute_on: '2025-12-19T00:00:00Z',
          type: 'credit',
          category: 'shopping',
        },
        {
          transaction_id: 2,
          user_id: 1,
          sender: '',
          receiver: '',
          name: 'Veum-Dare',
          amount: 20.26,
          recurring: null,
          recurring_id: null,
          theme: '#934f6f',
          budget_id: 4,
          deleted_at: null,
          created_at: '2025-02-24T16:14:01.000000Z',
          execute_on: '2025-12-19T00:00:00Z',
          type: 'credit',
          category: 'shopping',
        },
      ],
    },
    {
      id: 5,
      name: 'Dining Out',
      amount: 229.81,
      maximum: 258.82,
      theme: '#277C78',
      time_frame: 'month',
      deleted_at: null,
      created_at: '2025-02-24T16:14:01.000000Z',
      last_spendings: [
        {
          transaction_id: 1,
          user_id: 1,
          sender: '',
          receiver: '',
          name: 'Initial Deposit',
          amount: 100.0,
          recurring: null,
          recurring_id: null,
          theme: '#c94736',
          budget_id: null,
          deleted_at: null,
          created_at: '2025-02-24T16:14:01.000000Z',
          execute_on: '2025-12-19T00:00:00Z',
          type: 'credit',
          category: 'diningOut',
        },
        {
          transaction_id: 2,
          user_id: 1,
          sender: '',
          receiver: '',
          name: 'Veum-Dare',
          amount: 20.26,
          recurring: null,
          recurring_id: null,
          theme: '#82c9d7',
          budget_id: 4,
          deleted_at: null,
          created_at: '2025-02-24T16:14:01.000000Z',
          execute_on: '2025-12-19T00:00:00Z',
          type: 'credit',
          category: 'diningOut',
        },
      ],
    },
    {
      id: 6,
      name: 'Entertainment',
      amount: 316.83,
      maximum: 929.42,
      theme: '#826CB0',
      time_frame: 'quarter',
      deleted_at: null,
      created_at: '2025-02-24T16:14:01.000000Z',
      last_spendings: [
        {
          transaction_id: 1,
          user_id: 1,
          sender: '',
          receiver: '',
          name: 'Initial Deposit',
          amount: 100.0,
          recurring: null,
          recurring_id: null,
          theme: '#f2cdac',
          budget_id: null,
          deleted_at: null,
          created_at: '2025-02-24T16:14:01.000000Z',
          execute_on: '2025-12-19T00:00:00Z',
          type: 'credit',
          category: 'entertainment',
        },
        {
          transaction_id: 2,
          user_id: 1,
          sender: '',
          receiver: '',
          name: 'Veum-Dare',
          amount: 20.26,
          recurring: null,
          recurring_id: null,
          theme: '#826cb0',
          budget_id: 4,
          deleted_at: null,
          created_at: '2025-02-24T16:14:01.000000Z',
          execute_on: '2025-12-19T00:00:00Z',
          type: 'credit',
          category: 'entertainment',
        },
      ],
    },
  ]);

  // public pots = signal<PotsObject[]>([]);

  public pots = signal<PotsObject[]>([
    {
      id: 0,
      name: 'Savings',
      target: 2000.0,
      total: 159.0,
      theme: '#277C78',
      created_at: null,
      deleted_at: null,
    },
    {
      id: 1,
      name: 'Concert Ticket',
      target: 150.0,
      total: 110.0,
      theme: '#626070',
      created_at: null,
      deleted_at: null,
    },
    {
      id: 2,
      name: 'Gift',
      target: 150.0,
      total: 110.0,
      theme: '#82C9D7',
      created_at: null,
      deleted_at: null,
    },
    {
      id: 3,
      name: 'New Laptop',
      target: 1750.0,
      total: 10.0,
      theme: '#F2CDAC',
      created_at: null,
      deleted_at: null,
    },
    {
      id: 4,
      name: 'Holiday',
      target: 1440.0,
      total: 531.0,
      theme: '#826CB0',
      created_at: null,
      deleted_at: null,
    },
  ]);

  // public transactions = signal<TransactionsObject[]>([]);
  public transactions = signal<TransactionsObject[]>([
    {
      transaction_id: 0,
      user_id: 0,
      amount: 86.68,
      budget_id: null,
      created_at: '2025-09-12T00:00:00Z',
      execute_on: '2025-07-26T00:00:00Z',
      deleted_at: null,
      recurring: null,
      recurring_id: null,
      theme: '#597C7C',
      sender: '',
      receiver: '',
      name: 'Game Purchase',
      category: 'entertainment',
      type: 'debit',
    },
    {
      transaction_id: 1,
      user_id: 0,
      amount: 146.88,
      budget_id: null,
      created_at: '2025-02-09T00:00:00Z',
      execute_on: '2025-12-19T00:00:00Z',
      deleted_at: null,
      recurring: null,
      recurring_id: null,
      theme: '#626070',
      sender: '',
      receiver: '',
      name: 'Internet Bill',
      category: 'bills',
      type: 'debit',
    },
    {
      transaction_id: 2,
      user_id: 0,
      amount: 133.42,
      budget_id: null,
      created_at: '2025-06-14T00:00:00Z',
      execute_on: '2025-08-10T00:00:00Z',
      deleted_at: null,
      recurring: null,
      recurring_id: null,
      theme: '#97a0ac',
      sender: '',
      receiver: '',
      name: 'Organic Food Store',
      category: 'groceries',
      type: 'debit',
    },
    {
      transaction_id: 3,
      user_id: 0,
      amount: 49.81,
      budget_id: null,
      created_at: '2025-02-08T00:00:00Z',
      execute_on: '2025-06-02T00:00:00Z',
      deleted_at: null,
      recurring: null,
      recurring_id: null,
      theme: '#F2CDAC',
      sender: '',
      receiver: '',
      name: 'Caf\u00e9 Visit',
      category: 'diningOut',
      type: 'credit',
    },
    {
      transaction_id: 4,
      user_id: 0,
      amount: 170.55,
      budget_id: null,
      created_at: '2025-11-04T00:00:00Z',
      execute_on: '2025-07-30T00:00:00Z',
      deleted_at: null,
      recurring: null,
      recurring_id: null,
      theme: '#af81ba',
      sender: '',
      receiver: '',
      name: 'Taxi Ride',
      category: 'transportation',
      type: 'debit',
    },
    {
      transaction_id: 5,
      user_id: 0,
      amount: 42.36,
      budget_id: null,
      created_at: '2025-03-25T00:00:00Z',
      execute_on: '2025-01-16T00:00:00Z',
      deleted_at: null,
      recurring: null,
      recurring_id: null,
      theme: '#cab361',
      sender: '',
      receiver: '',
      name: 'Massage Session',
      category: 'personalCare',
      type: 'debit',
    },
    {
      transaction_id: 6,
      user_id: 0,
      amount: 78.76,
      budget_id: null,
      created_at: '2025-12-16T00:00:00Z',
      execute_on: '2025-08-29T00:00:00Z',
      deleted_at: null,
      recurring: null,
      recurring_id: null,
      theme: '#597C7C',
      sender: '',
      receiver: '',
      name: 'Bookstore Purchase',
      category: 'education',
      type: 'debit',
    },
    {
      transaction_id: 7,
      user_id: 0,
      amount: 195.52,
      budget_id: null,
      created_at: '2025-02-24T00:00:00Z',
      execute_on: '2025-05-04T00:00:00Z',
      deleted_at: null,
      recurring: null,
      recurring_id: null,
      theme: '#626070',
      sender: '',
      receiver: '',
      name: 'Concert Ticket',
      category: 'lifestyle',
      type: 'credit',
    },
    {
      transaction_id: 8,
      user_id: 0,
      amount: 195.05,
      budget_id: null,
      created_at: '2025-04-22T00:00:00Z',
      execute_on: '2025-06-14T00:00:00Z',
      deleted_at: null,
      recurring: null,
      recurring_id: null,
      theme: '#7f9161',
      sender: '',
      receiver: '',
      name: 'Tech Gadget',
      category: 'shopping',
      type: 'debit',
    },
    {
      transaction_id: 9,
      user_id: 0,
      amount: 102.74,
      budget_id: null,
      created_at: '2025-12-02T00:00:00Z',
      execute_on: '2025-05-14T00:00:00Z',
      deleted_at: null,
      recurring: null,
      recurring_id: null,
      theme: '#277C78',
      sender: '',
      receiver: '',
      name: 'Charity Donation',
      category: 'general',
      type: 'debit',
    },
    {
      transaction_id: 10,
      user_id: 0,
      amount: 151.12,
      budget_id: null,
      created_at: '2025-03-06T00:00:00Z',
      execute_on: '2025-11-10T00:00:00Z',
      deleted_at: null,
      recurring: null,
      recurring_id: null,
      theme: '#597C7C',
      sender: '',
      receiver: '',
      name: 'Event Entry',
      category: 'lifestyle',
      type: 'debit',
    },
    {
      transaction_id: 11,
      user_id: 0,
      amount: 148.6,
      budget_id: null,
      created_at: '2025-08-21T00:00:00Z',
      execute_on: '2025-11-10T00:00:00Z',
      deleted_at: null,
      recurring: null,
      recurring_id: null,
      theme: '#3F82B2',
      sender: '',
      receiver: '',
      name: 'Event Entry',
      category: 'lifestyle',
      type: 'credit',
    },
    {
      transaction_id: 12,
      user_id: 0,
      amount: 29.26,
      budget_id: null,
      created_at: '2025-05-01T00:00:00Z',
      execute_on: '2025-08-23T00:00:00Z',
      deleted_at: null,
      recurring: null,
      recurring_id: null,
      theme: '#C94736',
      sender: '',
      receiver: '',
      name: 'Organic Food Store',
      category: 'groceries',
      type: 'debit',
    },
    {
      transaction_id: 13,
      user_id: 0,
      amount: 69.97,
      budget_id: null,
      created_at: '2025-04-23T00:00:00Z',
      execute_on: '2025-11-17T00:00:00Z',
      deleted_at: null,
      recurring: null,
      recurring_id: null,
      theme: '#be6c49',
      sender: '',
      receiver: '',
      name: 'Furniture Purchase',
      category: 'shopping',
      type: 'debit',
    },
    {
      transaction_id: 14,
      user_id: 0,
      amount: 106.84,
      budget_id: null,
      created_at: '2025-10-15T00:00:00Z',
      execute_on: '2025-10-27T00:00:00Z',
      deleted_at: null,
      recurring: null,
      recurring_id: null,
      theme: '#d46c5e',
      sender: '',
      receiver: '',
      name: 'Organic Food Store',
      category: 'groceries',
      type: 'debit',
    },
    {
      transaction_id: 15,
      user_id: 0,
      amount: 173.57,
      budget_id: null,
      created_at: '2025-11-13T00:00:00Z',
      execute_on: '2025-07-21T00:00:00Z',
      deleted_at: null,
      recurring: null,
      recurring_id: null,
      theme: '#3F82B2',
      sender: '',
      receiver: '',
      name: 'Furniture Purchase',
      category: 'shopping',
      type: 'debit',
    },
    {
      transaction_id: 16,
      user_id: 0,
      amount: 66.79,
      budget_id: null,
      created_at: '2025-10-04T00:00:00Z',
      execute_on: '2025-08-12T00:00:00Z',
      deleted_at: null,
      recurring: null,
      recurring_id: null,
      theme: '#826CB0',
      sender: '',
      receiver: '',
      name: 'Organic Food Store',
      category: 'groceries',
      type: 'debit',
    },
    {
      transaction_id: 17,
      user_id: 0,
      amount: 96.04,
      budget_id: null,
      created_at: '2025-05-05T00:00:00Z',
      execute_on: '2025-03-21T00:00:00Z',
      deleted_at: null,
      recurring: null,
      recurring_id: null,
      theme: '#cab361',
      sender: '',
      receiver: '',
      name: 'Spa Treatment',
      category: 'personalCare',
      type: 'debit',
    },
    {
      transaction_id: 18,
      user_id: 0,
      amount: 110.48,
      budget_id: null,
      created_at: '2025-01-08T00:00:00Z',
      execute_on: '2025-10-21T00:00:00Z',
      deleted_at: null,
      recurring: null,
      recurring_id: null,
      theme: '#cab361',
      sender: '',
      receiver: '',
      name: 'Gas Bill',
      category: 'bills',
      type: 'debit',
    },
    {
      transaction_id: 19,
      user_id: 0,
      amount: 176.13,
      budget_id: null,
      created_at: '2025-04-16T00:00:00Z',
      execute_on: '2025-07-29T00:00:00Z',
      deleted_at: null,
      recurring: null,
      recurring_id: null,
      theme: '#C94736',
      sender: '',
      receiver: '',
      name: 'Concert Ticket',
      category: 'lifestyle',
      type: 'credit',
    },
    {
      transaction_id: 20,
      user_id: 0,
      amount: 36.52,
      budget_id: null,
      created_at: '2025-05-16T00:00:00Z',
      execute_on: '2025-10-21T00:00:00Z',
      deleted_at: null,
      recurring: null,
      recurring_id: null,
      theme: '#C94736',
      sender: '',
      receiver: '',
      name: 'Gym Membership',
      category: 'lifestyle',
      type: 'debit',
    },
    {
      transaction_id: 21,
      user_id: 0,
      amount: 113.45,
      budget_id: null,
      created_at: '2025-07-11T00:00:00Z',
      execute_on: '2025-10-18T00:00:00Z',
      deleted_at: null,
      recurring: null,
      recurring_id: null,
      theme: '#97a0ac',
      sender: '',
      receiver: '',
      name: 'Train Ticket',
      category: 'transportation',
      type: 'debit',
    },
    {
      transaction_id: 22,
      user_id: 0,
      amount: 78.34,
      budget_id: null,
      created_at: '2025-08-03T00:00:00Z',
      execute_on: '2025-08-10T00:00:00Z',
      deleted_at: null,
      recurring: null,
      recurring_id: null,
      theme: '#C94736',
      sender: '',
      receiver: '',
      name: 'Clothing Store',
      category: 'shopping',
      type: 'credit',
    },
    {
      transaction_id: 23,
      user_id: 0,
      amount: 124.95,
      budget_id: null,
      created_at: '2025-05-05T00:00:00Z',
      execute_on: '2025-12-23T00:00:00Z',
      deleted_at: null,
      recurring: null,
      recurring_id: null,
      theme: '#597C7C',
      sender: '',
      receiver: '',
      name: 'Bookstore Purchase',
      category: 'education',
      type: 'debit',
    },
    {
      transaction_id: 24,
      user_id: 0,
      amount: 17.62,
      budget_id: null,
      created_at: '2025-10-29T00:00:00Z',
      execute_on: '2025-08-22T00:00:00Z',
      deleted_at: null,
      recurring: null,
      recurring_id: null,
      theme: '#C94736',
      sender: '',
      receiver: '',
      name: 'Food Delivery',
      category: 'diningOut',
      type: 'debit',
    },
    {
      transaction_id: 25,
      user_id: 0,
      amount: 117.96,
      budget_id: null,
      created_at: '2025-07-20T00:00:00Z',
      execute_on: '2025-11-15T00:00:00Z',
      deleted_at: null,
      recurring: null,
      recurring_id: null,
      theme: '#af81ba',
      sender: '',
      receiver: '',
      name: 'Farmers Market',
      category: 'groceries',
      type: 'debit',
    },
    {
      transaction_id: 26,
      user_id: 0,
      amount: 186.54,
      budget_id: null,
      created_at: '2025-04-16T00:00:00Z',
      execute_on: '2025-12-12T00:00:00Z',
      deleted_at: null,
      recurring: null,
      recurring_id: null,
      theme: '#93674F',
      sender: '',
      receiver: '',
      name: 'Train Ticket',
      category: 'transportation',
      type: 'debit',
    },
    {
      transaction_id: 27,
      user_id: 0,
      amount: 87.18,
      budget_id: null,
      created_at: '2025-07-17T00:00:00Z',
      execute_on: '2025-07-22T00:00:00Z',
      deleted_at: null,
      recurring: null,
      recurring_id: null,
      theme: '#7f9161',
      sender: '',
      receiver: '',
      name: 'Bank Fee',
      category: 'general',
      type: 'debit',
    },
    {
      transaction_id: 28,
      user_id: 0,
      amount: 6.75,
      budget_id: null,
      created_at: '2025-08-01T00:00:00Z',
      execute_on: '2025-09-29T00:00:00Z',
      deleted_at: null,
      recurring: null,
      recurring_id: null,
      theme: '#d46c5e',
      sender: '',
      receiver: '',
      name: 'Gas Bill',
      category: 'bills',
      type: 'debit',
    },
    {
      transaction_id: 29,
      user_id: 0,
      amount: 70.69,
      budget_id: null,
      created_at: '2025-02-13T00:00:00Z',
      execute_on: '2025-01-27T00:00:00Z',
      deleted_at: null,
      recurring: null,
      recurring_id: null,
      theme: '#277C78',
      sender: '',
      receiver: '',
      name: 'Gym Membership',
      category: 'personalCare',
      type: 'debit',
    },
    {
      transaction_id: 30,
      user_id: 0,
      amount: 83.1,
      budget_id: null,
      created_at: '2025-07-26T00:00:00Z',
      execute_on: '2025-02-17T00:00:00Z',
      deleted_at: null,
      recurring: null,
      recurring_id: null,
      theme: '#af81ba',
      sender: '',
      receiver: '',
      name: 'Furniture Purchase',
      category: 'shopping',
      type: 'debit',
    },
    {
      transaction_id: 31,
      user_id: 0,
      amount: 178.55,
      budget_id: null,
      created_at: '2025-04-19T00:00:00Z',
      execute_on: '2025-02-26T00:00:00Z',
      deleted_at: null,
      recurring: null,
      recurring_id: null,
      theme: '#82C9D7',
      sender: '',
      receiver: '',
      name: 'Service Charge',
      category: 'general',
      type: 'debit',
    },
    {
      transaction_id: 32,
      user_id: 0,
      amount: 105.78,
      budget_id: null,
      created_at: '2025-10-28T00:00:00Z',
      execute_on: '2025-02-28T00:00:00Z',
      deleted_at: null,
      recurring: null,
      recurring_id: null,
      theme: '#af81ba',
      sender: '',
      receiver: '',
      name: 'Bookstore Purchase',
      category: 'education',
      type: 'credit',
    },
    {
      transaction_id: 33,
      user_id: 0,
      amount: 153.54,
      budget_id: null,
      created_at: '2025-08-30T00:00:00Z',
      execute_on: '2025-10-11T00:00:00Z',
      deleted_at: null,
      recurring: null,
      recurring_id: null,
      theme: '#597C7C',
      sender: '',
      receiver: '',
      name: 'Wholesale Grocery',
      category: 'groceries',
      type: 'debit',
    },
    {
      transaction_id: 34,
      user_id: 0,
      amount: 21.78,
      budget_id: null,
      created_at: '2025-10-04T00:00:00Z',
      execute_on: '2025-03-09T00:00:00Z',
      deleted_at: null,
      recurring: null,
      recurring_id: null,
      theme: '#7f9161',
      sender: '',
      receiver: '',
      name: 'Haircut',
      category: 'personalCare',
      type: 'debit',
    },
    {
      transaction_id: 35,
      user_id: 0,
      amount: 92.24,
      budget_id: null,
      created_at: '2025-04-22T00:00:00Z',
      execute_on: '2025-12-24T00:00:00Z',
      deleted_at: null,
      recurring: null,
      recurring_id: null,
      theme: '#626070',
      sender: '',
      receiver: '',
      name: 'Supermarket Purchase',
      category: 'groceries',
      type: 'debit',
    },
    {
      transaction_id: 36,
      user_id: 0,
      amount: 32.3,
      budget_id: null,
      created_at: '2025-02-17T00:00:00Z',
      execute_on: '2025-11-04T00:00:00Z',
      deleted_at: null,
      recurring: null,
      recurring_id: null,
      theme: '#277C78',
      sender: '',
      receiver: '',
      name: 'Cinema Ticket',
      category: 'entertainment',
      type: 'debit',
    },
    {
      transaction_id: 37,
      user_id: 0,
      amount: 90.88,
      budget_id: null,
      created_at: '2025-09-30T00:00:00Z',
      execute_on: '2025-03-09T00:00:00Z',
      deleted_at: null,
      recurring: null,
      recurring_id: null,
      theme: '#F2CDAC',
      sender: '',
      receiver: '',
      name: 'Event Entry',
      category: 'lifestyle',
      type: 'debit',
    },
    {
      transaction_id: 38,
      user_id: 0,
      amount: 112.69,
      budget_id: null,
      created_at: '2025-05-05T00:00:00Z',
      execute_on: '2025-04-23T00:00:00Z',
      deleted_at: null,
      recurring: null,
      recurring_id: null,
      theme: '#7f9161',
      sender: '',
      receiver: '',
      name: 'Fuel Purchase',
      category: 'transportation',
      type: 'debit',
    },
    {
      transaction_id: 39,
      user_id: 0,
      amount: 158.94,
      budget_id: null,
      created_at: '2025-01-04T00:00:00Z',
      execute_on: '2025-10-06T00:00:00Z',
      deleted_at: null,
      recurring: null,
      recurring_id: null,
      theme: '#97a0ac',
      sender: '',
      receiver: '',
      name: 'Gym Membership',
      category: 'lifestyle',
      type: 'credit',
    },
    {
      transaction_id: 40,
      user_id: 0,
      amount: 61.63,
      budget_id: null,
      created_at: '2025-11-20T00:00:00Z',
      execute_on: '2025-01-25T00:00:00Z',
      deleted_at: null,
      recurring: null,
      recurring_id: null,
      theme: '#826CB0',
      sender: '',
      receiver: '',
      name: 'Supermarket Purchase',
      category: 'groceries',
      type: 'debit',
    },
    {
      transaction_id: 41,
      user_id: 0,
      amount: 8.13,
      budget_id: null,
      created_at: '2025-03-02T00:00:00Z',
      execute_on: '2025-05-21T00:00:00Z',
      deleted_at: null,
      recurring: null,
      recurring_id: null,
      theme: '#277C78',
      sender: '',
      receiver: '',
      name: 'Concert Ticket',
      category: 'lifestyle',
      type: 'debit',
    },
    {
      transaction_id: 42,
      user_id: 0,
      amount: 180.87,
      budget_id: null,
      created_at: '2025-05-16T00:00:00Z',
      execute_on: '2025-04-08T00:00:00Z',
      deleted_at: null,
      recurring: null,
      recurring_id: null,
      theme: '#626070',
      sender: '',
      receiver: '',
      name: 'Online Course Fee',
      category: 'education',
      type: 'credit',
    },
    {
      transaction_id: 43,
      user_id: 0,
      amount: 191.42,
      budget_id: null,
      created_at: '2025-02-10T00:00:00Z',
      execute_on: '2025-11-14T00:00:00Z',
      deleted_at: null,
      recurring: null,
      recurring_id: null,
      theme: '#3F82B2',
      sender: '',
      receiver: '',
      name: 'Spa Treatment',
      category: 'personalCare',
      type: 'debit',
    },
    {
      transaction_id: 44,
      user_id: 0,
      amount: 67.27,
      budget_id: null,
      created_at: '2025-10-13T00:00:00Z',
      execute_on: '2025-03-11T00:00:00Z',
      deleted_at: null,
      recurring: null,
      recurring_id: null,
      theme: '#3F82B2',
      sender: '',
      receiver: '',
      name: 'Gas Bill',
      category: 'bills',
      type: 'debit',
    },
    {
      transaction_id: 2,
      user_id: 0,
      amount: 133.42,
      budget_id: null,
      created_at: '2024-06-14T00:00:00Z',
      execute_on: '2025-03-10T00:00:00Z',
      deleted_at: null,
      recurring: 'monthly',
      recurring_id: 2,
      theme: '#97a0ac',
      sender: '',
      receiver: '',
      name: 'Car Loan',
      category: 'bills',
      type: 'debit',
    },
    {
      transaction_id: 3,
      user_id: 0,
      amount: 49.81,
      budget_id: null,
      created_at: '2025-02-08T00:00:00Z',
      execute_on: '2025-03-02T00:00:00Z',
      deleted_at: null,
      recurring: 'monthly',
      recurring_id: 3,
      theme: '#F2CDAC',
      sender: '',
      receiver: '',
      name: 'Car Insurance',
      category: 'bills',
      type: 'debit',
    },
    {
      transaction_id: 5,
      user_id: 0,
      amount: 42.36,
      budget_id: null,
      created_at: '2024-03-25T00:00:00Z',
      execute_on: '2025-03-16T00:00:00Z',
      deleted_at: null,
      recurring: 'monthly',
      recurring_id: 5,
      theme: '#cab361',
      sender: '',
      receiver: '',
      name: 'Energy Bill',
      category: 'bills',
      type: 'credit',
    },
    {
      transaction_id: 0,
      user_id: 0,
      amount: 345.0,
      budget_id: null,
      created_at: '2024-09-12T00:00:00Z',
      execute_on: '2025-02-26T00:00:00Z',
      deleted_at: null,
      recurring: 'monthly',
      recurring_id: 0,
      theme: '#597C7C',
      sender: '',
      receiver: '',
      name: 'Apartment Rent',
      category: 'bills',
      type: 'debit',
    },
    {
      transaction_id: 1,
      user_id: 0,
      amount: 146.88,
      budget_id: null,
      created_at: '2025-02-09T00:00:00Z',
      execute_on: '2025-02-19T00:00:00Z',
      deleted_at: null,
      recurring: 'monthly',
      recurring_id: 1,
      theme: '#626070',
      sender: '',
      receiver: '',
      name: 'Internet Bill',
      category: 'bills',
      type: 'debit',
    },
    {
      transaction_id: 2,
      user_id: 0,
      amount: 133.42,
      budget_id: null,
      created_at: '2024-06-14T00:00:00Z',
      execute_on: '2025-02-10T00:00:00Z',
      deleted_at: null,
      recurring: 'monthly',
      recurring_id: 2,
      theme: '#97a0ac',
      sender: '',
      receiver: '',
      name: 'Car Loan',
      category: 'bills',
      type: 'debit',
    },
    {
      transaction_id: 4,
      user_id: 0,
      amount: 45.0,
      budget_id: null,
      created_at: '2024-11-04T00:00:00Z',
      execute_on: '2025-02-28T00:00:00Z',
      deleted_at: null,
      recurring: 'monthly',
      recurring_id: 4,
      theme: '#af81ba',
      sender: '',
      receiver: '',
      name: 'Gym',
      category: 'bills',
      type: 'debit',
    },
    {
      transaction_id: 5,
      user_id: 0,
      amount: 42.36,
      budget_id: null,
      created_at: '2024-03-25T00:00:00Z',
      execute_on: '2025-02-16T00:00:00Z',
      deleted_at: null,
      recurring: 'monthly',
      recurring_id: 5,
      theme: '#cab361',
      sender: '',
      receiver: '',
      name: 'Energy Bill',
      category: 'bills',
      type: 'credit',
    },
    {
      transaction_id: 6,
      user_id: 0,
      amount: 40.0,
      budget_id: null,
      created_at: '2024-03-25T00:00:00Z',
      execute_on: '2025-03-17T00:00:00Z',
      deleted_at: null,
      recurring: 'weekly',
      recurring_id: 6,
      theme: '#cab361',
      sender: '',
      receiver: '',
      name: 'Office Rent',
      category: 'bills',
      type: 'debit',
    },
    {
      transaction_id: 7,
      user_id: 0,
      amount: 100.0,
      budget_id: null,
      created_at: '2024-03-25T00:00:00Z',
      execute_on: '2025-01-24T00:00:00Z',
      deleted_at: null,
      recurring: 'quarterly',
      recurring_id: 7,
      theme: '#cab361',
      sender: '',
      receiver: '',
      name: 'Water Bill',
      category: 'bills',
      type: 'debit',
    },
  ]);

  // public transactionsRecurring = signal<TransactionsObject[]>([]);
  public transactionsRecurring = signal<TransactionsObject[]>([
    {
      transaction_id: 0,
      user_id: 0,
      amount: 345.0,
      budget_id: null,
      created_at: '2024-09-12T00:00:00Z',
      execute_on: '2025-03-26T00:00:00Z',
      deleted_at: null,
      recurring: 'monthly',
      recurring_id: 0,
      theme: '#597C7C',
      sender: '',
      receiver: '',
      name: 'Apartment Rent',
      category: 'bills',
      type: 'debit',
    },
    {
      transaction_id: 1,
      user_id: 0,
      amount: 146.88,
      budget_id: null,
      created_at: '2025-02-09T00:00:00Z',
      execute_on: '2025-03-19T00:00:00Z',
      deleted_at: null,
      recurring: 'monthly',
      recurring_id: 1,
      theme: '#626070',
      sender: '',
      receiver: '',
      name: 'Internet Bill',
      category: 'bills',
      type: 'debit',
    },
    {
      transaction_id: 2,
      user_id: 0,
      amount: 133.42,
      budget_id: null,
      created_at: '2024-06-14T00:00:00Z',
      execute_on: '2025-04-10T00:00:00Z',
      deleted_at: null,
      recurring: 'monthly',
      recurring_id: 2,
      theme: '#97a0ac',
      sender: '',
      receiver: '',
      name: 'Car Loan',
      category: 'bills',
      type: 'debit',
    },
    {
      transaction_id: 3,
      user_id: 0,
      amount: 49.81,
      budget_id: null,
      created_at: '2025-02-08T00:00:00Z',
      execute_on: '2025-04-02T00:00:00Z',
      deleted_at: null,
      recurring: 'monthly',
      recurring_id: 3,
      theme: '#F2CDAC',
      sender: '',
      receiver: '',
      name: 'Car Insurance',
      category: 'bills',
      type: 'debit',
    },
    {
      transaction_id: 4,
      user_id: 0,
      amount: 45.0,
      budget_id: null,
      created_at: '2024-11-04T00:00:00Z',
      execute_on: '2025-03-30T00:00:00Z',
      deleted_at: null,
      recurring: 'monthly',
      recurring_id: 4,
      theme: '#af81ba',
      sender: '',
      receiver: '',
      name: 'Gym',
      category: 'bills',
      type: 'debit',
    },
    {
      transaction_id: 5,
      user_id: 0,
      amount: 42.36,
      budget_id: null,
      created_at: '2024-03-25T00:00:00Z',
      execute_on: '2025-04-16T00:00:00Z',
      deleted_at: null,
      recurring: 'monthly',
      recurring_id: 5,
      theme: '#cab361',
      sender: '',
      receiver: '',
      name: 'Energy Bill',
      category: 'bills',
      type: 'debit',
    },
    {
      transaction_id: 6,
      user_id: 0,
      amount: 40.0,
      budget_id: null,
      created_at: '2024-03-25T00:00:00Z',
      execute_on: '2025-03-23T00:00:00Z',
      deleted_at: null,
      recurring: 'weekly',
      recurring_id: 6,
      theme: '#cab361',
      sender: '',
      receiver: '',
      name: 'Office Rent',
      category: 'bills',
      type: 'debit',
    },
    {
      transaction_id: 7,
      user_id: 0,
      amount: 100.0,
      budget_id: null,
      created_at: '2024-03-25T00:00:00Z',
      execute_on: '2025-04-24T00:00:00Z',
      deleted_at: null,
      recurring: 'quarterly',
      recurring_id: 7,
      theme: '#cab361',
      sender: '',
      receiver: '',
      name: 'Water Bill',
      category: 'bills',
      type: 'debit',
    },
    {
      transaction_id: 8,
      user_id: 0,
      amount: 200.0,
      budget_id: null,
      created_at: '2025-03-21T00:00:00Z',
      execute_on: '2025-03-23T00:00:00Z',
      deleted_at: null,
      recurring: 'quarterly',
      recurring_id: 8,
      theme: '#cab361',
      sender: '',
      receiver: '',
      name: 'Test 2 Months',
      category: 'bills',
      type: 'debit',
    },
  ]);

  constructor() {}

  // set the hole data package within signal and UI update
  setStoredData(endpoint: string, data: any) {
    if (endpoint === 'settings') this.settings.set(data);
    if (endpoint === 'balance') this.balance.set(data);
    if (endpoint === 'budgets') this.budgets.set(data);
    if (endpoint === 'pots') this.pots.set(data);
    if (endpoint === 'transactions') this.transactions.set(data);
    if (endpoint === 'recurrings') this.transactionsRecurring.set(data);
  }

  // get the hole data package without signal and UI update
  public getStoredData(endpoint: string) {
    if (endpoint === 'balance') return this.balance;
    if (endpoint === 'budgets') return this.budgets;
    if (endpoint === 'pots') return this.pots;
    if (endpoint === 'transactions') return this.transactions;
    if (endpoint === 'recurrings') return this.transactionsRecurring;
    return null;
  }

  // add new data to the existing dataArray and update the signal and UI
  public addToStoredData(endpoint: string, data: any) {
    if (endpoint === 'budgets') this.budgets.update((prev) => [data, ...prev]);
    if (endpoint === 'pots') this.pots.update((prev) => [data, ...prev]);
    if (endpoint === 'transactions')
      this.transactions.update((prev) => [...prev, data]);
    if (endpoint === 'recurrings')
      this.transactionsRecurring.update((prev) => [...prev, data]);
  }

  // chose what kind of data to soft delete and update the signal and UI
  public choseDataAndSoftDelete(endpoint: string, index: number) {
    if (endpoint === 'budgets' && index >= 0)
      this.budgets.update((prev) => {
        return this.softDeleteData(prev, index);
      });
    if (endpoint === 'pots' && index >= 0)
      this.pots.update((prev) => {
        return this.softDeleteData(prev, index);
      });
    if (endpoint === 'recurrings' && index >= 0)
      this.transactionsRecurring.update((prev) => {
        return this.softDeleteData(prev, index);
      });
  }

  // soft delete data
  public softDeleteData(prev: any, index: number) {
    let array = [...prev];
    array[index].deleted_at = new Date().toISOString();
    return array;
  }

  // update the balance and update the signal and UI
  public updateStoredBalance(key: string, amount: number) {
    this.balance.update((prev) => {
      let prevBalance = { ...prev };
      // if (key === 'current') prevBalance.current += amount;
      // if (key === 'income') prevBalance.income += amount;
      // if (key === 'expenses') prevBalance.expenses += amount;
      return prevBalance;
    });
  }

  // update the existing data and update the signal and UI
  public editStoredData(endpoint: string, index: number, data: any) {
    if (endpoint === 'budgets' && data && index >= 0) {
      this.budgets.update((prev) => {
        return prev.map((item, i) => (i === index ? { ...data } : item));
      });
    }

    if (endpoint === 'pots' && data && index >= 0) {
      this.pots.update((prev) => {
        return prev.map((item, i) => (i === index ? { ...data } : item));
      });
    }
  }
}
